# ============================================================================
# S0_environment_lock.R  (v3 — 2026-09-12)
# v3 change: lisi moved out of cran_pkgs — verified 2026-09-12 that its CRAN
# page returns 404 (no longer on CRAN); installed from GitHub
# (immunogenomics/lisi). It stays GATE-REQUIRED (S2 batch-mixing metric),
# unlike monocle3/CellChat which remain deferred/non-fatal.
# ============================================================================
# Project: Benign Immunoediting in Endometriosis
# Purpose: initialize renv, install the locked package set, VERIFY every
#          package loads, export renv.lock + sessionInfo.
# Charter ref: Section 5, stage S0; rules R2/R4 (traceability, no manual edits).
#
# HOW TO RUN (important — v1 failure was an execution accident, not data):
#   1. Do NOT edit this file and do NOT paste it into the console in chunks.
#      Run it whole:  source("scripts/S0_environment_lock.R")
#      (pasting line-by-line skipped the install section in the v1 run, and
#       an edited self-sourcing copy caused the "node stack overflow" error)
#   2. The script is IDEMPOTENT: if RStudio restarts the session mid-run
#      (renv::init does that), simply source() it again until you see
#      "S0 done". Nothing is harmed by re-running.
#   3. Expect 20-60 min on first run (Seurat + Bioconductor stack).
# ============================================================================

# ---- 1. renv bootstrap (isolated project library) ----------------------------
if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
if (!dir.exists("renv")) renv::init(bare = TRUE) else renv::activate()

# Guard: installs must land in the PROJECT library, not your personal one.
# (v1 run snapshotted the personal library -> contaminated lockfile)
if (!grepl("renv", .libPaths()[1], fixed = TRUE))
  stop("renv project library is not active (.libPaths()[1] = ", .libPaths()[1],
       ").\nRestart R inside the project folder, then source() this script again.")

# ---- 2. Required package set (fixed; classifications corrected in v2) --------
cran_pkgs <- c(
  "Seurat", "SeuratObject", "harmony",          # S2 integration
  "Matrix", "data.table", "tidyverse", "patchwork",
  "pheatmap", "RColorBrewer", "ggrepel",
  "pbapply", "future.apply",
  "hdf5r"                                       # v3.2: required by Seurat::Read10X_h5
                                                # (Suggests of Seurat — never auto-installed)
)
bioc_pkgs <- c(
  "GEOquery", "Biobase", "limma",               # acquisition + bulk (moved from
                                                # the CRAN list — they are Bioc)
  "AUCell", "GSEABase",                         # S3 module scoring
  "SingleCellExperiment", "SummarizedExperiment",
  "GenomicRanges", "BiocParallel",
  "scDblFinder",                                # S2 doublets (pre-registered)
  "affy", "oligo", "arrayQualityMetrics",       # S2 bulk microarray QC
  "tradeSeq",                                   # S5 switch-point detection
  "clusterProfiler", "org.Hs.eg.db",            # enrichment
  "GENIE3",                                     # S7 regulons
  "BiocVersion",                                # version-marker required by the
                                                # affy/oligo binary stack; without it
                                                # renv::snapshot pre-flight aborts
  "pd.hg.u133.plus.2", "pd.hg.u133a"            # v3.2: oligo platform-design packages
                                                # for GPL570 / GPL96 CEL reading (S2_03);
                                                # pre-installed to avoid interactive prompts
)
# ---- 2b. GitHub-only but GATE-REQUIRED ----------------------------------------
# lisi (S2 batch-mixing metric, pre-registered in logs/S2_preregistered_design.md)
# is NOT on CRAN (its CRAN page returns 404, verified 2026-09-12). Install from
# GitHub. Unlike monocle3/CellChat this is NOT optional: if it fails, S0 fails.
github_required <- "lisi"
tryCatch({
  if (!requireNamespace("lisi", quietly = TRUE))
    renv::install("immunogenomics/lisi")
}, error = function(e) message("lisi GitHub install attempt failed: ",
                               conditionMessage(e), " — verification gate will catch it."))

# Deferred to their stages (NOT required for the S0 gate): monocle3 and CellChat
# are GitHub-only; heavy and need Rtools on Windows. Attempted non-fatally here;
# if they fail now they are retried at the S5/S6 gates without blocking S2.
if (!requireNamespace("remotes", quietly = TRUE)) renv::install("remotes")
gh_status <- c(
  monocle3 = tryCatch({
    if (!requireNamespace("monocle3", quietly = TRUE))
      remotes::install_github("cole-trapnell-lab/monocle3", upgrade = "never")
    requireNamespace("monocle3", quietly = TRUE)
  }, error = function(e) FALSE),
  CellChat = tryCatch({
    if (!requireNamespace("CellChat", quietly = TRUE))
      remotes::install_github("sqjin/CellChat", upgrade = "never")
    requireNamespace("CellChat", quietly = TRUE)
  }, error = function(e) FALSE)
)

# ---- 3. Install (renv resolves CRAN + Bioconductor automatically) ------------
options(Ncpus = max(1L, parallel::detectCores() - 1L))
renv::install(c(cran_pkgs, bioc_pkgs))

# ---- 4. Verification gate (binary, auditable — the lockfile alone is not) ----
required_now <- c(cran_pkgs, bioc_pkgs, github_required)
chk <- data.frame(
  package   = c(required_now, names(gh_status)),
  required  = c(rep("S0 gate", length(required_now)), rep("deferred (S5/S6)", 2)),
  installed = c(vapply(required_now, function(p) requireNamespace(p, quietly = TRUE), logical(1)),
                unname(gh_status)),
  version   = vapply(c(required_now, names(gh_status)), function(p)
    if (requireNamespace(p, quietly = TRUE)) as.character(utils::packageVersion(p)) else NA_character_,
    character(1)),
  stringsAsFactors = FALSE
)
dir.create("logs", showWarnings = FALSE)
write.csv(chk, "logs/S0_package_check.csv", row.names = FALSE)
print(chk)
missing <- chk$package[chk$required == "S0 gate" & !chk$installed]
if (length(missing))
  stop("S0 INCOMPLETE — missing packages: ", paste(missing, collapse = ", "),
       "\nRe-source this script; if a package keeps failing, send the console output.")

# ---- 5. Lock + session info ---------------------------------------------------
renv::snapshot(prompt = FALSE, type = "all")   # project library is isolated now:
                                               # "all" == exactly what we installed
sink("logs/sessionInfo_S0.txt")
cat("S0 environment lock — sessionInfo\n")
cat("Generated:", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "\n\n")
print(sessionInfo())
sink()

message("S0 done. Upload back: renv.lock, logs/sessionInfo_S0.txt, logs/S0_package_check.csv")
